Assignment1BasicApexTasks obj = new Assignment1BasicApexTasks();

List<Integer> numbers1 = new List<Integer>{8, 0,7,9,11};

List<Integer> numbers2 = new List<Integer>{8,3,56, 7, 3, 2, 7,9,11};

System.debug(obj.findCommonElementsInTwoList(numbers1, numbers2));

// List<Integer> result = obj.descendingSortList(numbers);
// System.debug(result);

// obj.findLargestAndSmallest(numbers);
obj.secondLargest(numbers);

// newList.add(5);
// newList.add(5);
// newList.add(6);
// newList.add(0);
// newList.add(4);
// newList.add(0);
// newList.add(8);
// obj.removeDuplicates(numbers);

// obj.checkArmstrongNum(153);

// System.debug('Sum of Digits of a Number :::: ' + obj.sumDigitOfNumber(154));

// List<Integer> integerList = new List<Integer>();
// for(Integer i = 1; i <= 31; i++) {
//     integerList.add(i);
// }
// List<Integer> result = new List<Integer>();
// result.addAll(obj.countEvenOdd(integerList));
// System.debug('Even Count ::::: ' + result[0]);
// System.debug('Odd Count  ::::: ' + result[1]);

// String result = obj.reverseString('Salesforce');
// System.debug(result);
// obj.CheckPalindrome('Pikachu');
// obj.CheckPalindrome('Radar');
// obj.CheckPalindrome('');


// obj.countVowelsAndConsonants('my name Is --->>>...Jatin SharmA');
// obj.countVowelsAndConsonants('');